apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ditto-gateway.fullname" . }}-config
  labels:
    {{- include "ditto-gateway.labels" . | nindent 4 }}
data:
  {{ .Values.gateway.configFileName }}: |-
    {{- .Values.gateway.configJson | nindent 4 }}
